#!/bin/bash

# Переход в домашнюю директорию
cd $HOME

# Скачивание node_exporter
wget https://github.com/prometheus/node_exporter/releases/download/v1.2.0/node_exporter-1.2.0.linux-amd64.tar.gz

# Распаковка архива
tar xvf node_exporter-1.2.0.linux-amd64.tar.gz

# Удаление архива после распаковки
rm node_exporter-1.2.0.linux-amd64.tar.gz

# Перемещение и подготовка к установке
sudo mv node_exporter-1.2.0.linux-amd64 node_exporter
chmod +x $HOME/node_exporter/node_exporter

# Установка файла в системный каталог
sudo mv $HOME/node_exporter/node_exporter /usr/bin

# Очистка
rm -Rvf $HOME/node_exporter/

# Создание systemd unit
sudo tee /etc/systemd/system/exporterd.service > /dev/null <<EOF
[Unit]
Description=node_exporter
After=network-online.target

[Service]
User=$USER
ExecStart=/usr/bin/node_exporter
Restart=always
RestartSec=3
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
EOF

# Перезагрузка демона systemd, включение и перезапуск сервиса node_exporter
sudo systemctl daemon-reload
sudo systemctl enable exporterd
sudo systemctl restart exporterd

# Просмотр логов сервиса
sudo journalctl -u exporterd -f
